FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY server ./server
WORKDIR /app/server
ENV APP_MODE=production PORT=4000 DB_PATH=/data/db.json
EXPOSE 4000
CMD ["node","src/index.js"]
