<script setup>
import { computed,onBeforeUnmount,onMounted,nextTick,ref } from 'vue';
import { api } from '../api';
import { IonContent,IonPage,IonButton } from '@ionic/vue';

const data=ref(null),busy=ref(false),signing=ref(null),tracking=ref({active:false,status:'OFFLINE',last:null,error:null});
const receiverName=ref(''),remarks=ref('');
let refreshTimer; let watchId=null,canvas=null,ctx=null,drawing=false,lastSent=0;
async function load(){ data.value=(await api.get('/dashboard')).data; syncTrackingFromData(); }
const runs=computed(()=>data.value?.routeRuns||[]);
const activeRun=computed(()=>runs.value.find(r=>r.status==='IN_PROGRESS')||runs.value.find(r=>r.status==='ASSIGNED')||null);
const nextStop=computed(()=>activeRun.value?.stops?.find(s=>!['COMPLETED','SKIPPED'].includes(s.status))||null);
const runDeliveries=computed(()=>activeRun.value?(data.value?.deliveries||[]).filter(d=>d.routeRunId===activeRun.value.id):[]);
const totalUnits=computed(()=>runDeliveries.value.reduce((s,d)=>s+(d.items||[]).reduce((a,i)=>a+Number(i.qty||0),0),0));
const routeInstructions=computed(()=>{const r=activeRun.value;if(!r)return[];const list=[];if(r.managerNote)list.push({rule:r.managerNote,critical:true,source:'Manager'});for(const st of r.stops||[])for(const x of st.instructions||[]){if(typeof x==='string')list.push({rule:x,critical:false,source:st.name});else list.push({...x,source:st.name});}return list;});
const instructionsRequired=computed(()=>routeInstructions.value.length>0);
const instructionsAcked=computed(()=>Boolean(activeRun.value?.instructionAcknowledgement));
function syncTrackingFromData(){ if(activeRun.value){tracking.value.status=activeRun.value.trackingStatus||'OFFLINE';tracking.value.last=activeRun.value.lastLocation||null;if(activeRun.value.status==='IN_PROGRESS'&&!watchId)startGps(activeRun.value.id);} }
onMounted(()=>{load();refreshTimer=setInterval(()=>{if(!document.hidden&&!signing.value&&!busy.value)load().catch(()=>{});},15000)});onBeforeUnmount(()=>{stopGps();clearInterval(refreshTimer)});
function locateOnce(){return new Promise(resolve=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),()=>resolve({}),{enableHighAccuracy:true,timeout:5000,maximumAge:15000}):resolve({}))}
async function acknowledge(run){busy.value=true;try{await api.post(`/route-runs/${run.id}/instructions/ack`);await load()}catch(e){alert(e.response?.data?.error||e.message)}finally{busy.value=false}}
async function startRun(run){if(instructionsRequired.value&&!instructionsAcked.value)return alert('Review and acknowledge the route instructions before pickup.');busy.value=true;try{const coords=await locateOnce();await api.post(`/route-runs/${run.id}/start`,coords);await load();startGps(run.id);}catch(e){alert(e.response?.data?.error||e.message)}finally{busy.value=false}}
function startGps(runId){if(!navigator.geolocation||watchId)return;tracking.value.active=true;tracking.value.error=null;watchId=navigator.geolocation.watchPosition(async p=>{tracking.value.status='LIVE';tracking.value.last={latitude:p.coords.latitude,longitude:p.coords.longitude,timestamp:new Date().toISOString()};const now=Date.now();if(now-lastSent<25000)return;lastSent=now;try{await api.post(`/route-runs/${runId}/location`,{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,heading:p.coords.heading})}catch{}},e=>{tracking.value.status='OFFLINE';tracking.value.error=e.message},{enableHighAccuracy:true,maximumAge:15000,timeout:20000});}
function stopGps(){if(watchId!=null&&navigator.geolocation){navigator.geolocation.clearWatch(watchId);watchId=null;}tracking.value.active=false;}
function nav(stop,provider='google'){if(!stop?.lat||!stop?.lng)return;const dest=`${stop.lat},${stop.lng}`;const urls={google:`https://www.google.com/maps/dir/?api=1&destination=${dest}`,waze:`https://waze.com/ul?ll=${dest}&navigate=yes`,apple:`https://maps.apple.com/?daddr=${dest}&dirflg=d`};window.open(urls[provider],'_blank');}
async function completeStop(run,stop){busy.value=true;try{await api.post(`/route-runs/${run.id}/stops/${stop.id}/complete`,{method:'MOBILE'});await load();if(activeRun.value?.status==='COMPLETED')stopGps()}finally{busy.value=false}}
async function openSign(run,stop){signing.value={run,stop};receiverName.value='';remarks.value='';await nextTick();canvas=document.getElementById('signature-pad');ctx=canvas.getContext('2d');const ratio=Math.max(window.devicePixelRatio||1,1),rect=canvas.getBoundingClientRect();canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;ctx.scale(ratio,ratio);ctx.lineWidth=2;ctx.lineCap='round';ctx.strokeStyle='#111827';}
function point(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:p.clientX-r.left,y:p.clientY-r.top}}function start(e){e.preventDefault();drawing=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)}function move(e){if(!drawing)return;e.preventDefault();const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke()}function end(){drawing=false}function clearSignature(){ctx&&canvas&&ctx.clearRect(0,0,canvas.width,canvas.height)}
async function submitSignoff(){if(!receiverName.value.trim())return alert('Receiver name is required.');busy.value=true;try{const coords=await locateOnce();await api.post(`/route-runs/${signing.value.run.id}/stops/${signing.value.stop.id}/signoff`,{receiverName:receiverName.value,remarks:remarks.value,signatureDataUrl:canvas.toDataURL('image/png'),...coords});signing.value=null;await load();if(activeRun.value?.status==='COMPLETED')stopGps()}catch(e){alert(e.response?.data?.error||e.message)}finally{busy.value=false}}
const fmt=t=>t?new Date(t).toLocaleString():'-';
</script>
<template><ion-page><ion-content>
<div class="mob-hero"><small>DRIVER OPERATIONS</small><h1>Today's route</h1><p>Confirm pickup once, then FlowDepot tracks the route while you drive. Use the phone again at each handover.</p></div>
<div v-if="data" class="statgrid"><div class="stat"><b>{{runs.length}}</b><span>ROUTES</span></div><div class="stat"><b>{{data.metrics.inTransit}}</b><span>IN TRANSIT</span></div><div class="stat"><b>{{data.metrics.completed}}</b><span>DELIVERED</span></div></div>

<div v-if="activeRun" class="job route-run-card">
  <div class="jobtop"><div><h3>{{activeRun.name}}</h3><small>{{activeRun.id}} · {{fmt(activeRun.scheduledAt)}}</small></div><span class="pillm">{{String(activeRun.status).replaceAll('_',' ')}}</span></div>
  <div class="run-people"><span><b>Primary</b>{{activeRun.primaryDriverName}}</span><span><b>Standby</b>{{activeRun.standbyDriverName}} <i v-if="activeRun.standbyApproved">✓ approved</i></span><span><b>Vehicle</b>{{activeRun.vehiclePlate}}</span></div>
  <div v-if="routeInstructions.length" class="pickup-summary"><b>Important route & cargo instructions</b><div v-for="(x,i) in routeInstructions" :key="i" style="margin-top:8px"><span class="pillm">{{x.critical?'IMPORTANT':'NOTE'}}</span> <strong>{{x.rule.replaceAll('_',' ')}}</strong><small style="display:block">{{x.source}}</small></div><ion-button v-if="!instructionsAcked" expand="block" fill="outline" :disabled="busy" @click="acknowledge(activeRun)">Acknowledge instructions</ion-button><small v-else>✓ Instructions acknowledged and recorded in audit trail.</small></div>
  <div v-if="activeRun.status==='ASSIGNED'" class="pickup-summary"><b>Pickup summary</b><span>{{activeRun.deliveryCount}} deliveries · {{totalUnits}} units · {{activeRun.totalStops-1}} onward stops</span><small>One confirmation starts the whole route. All linked deliveries become In Transit.</small><ion-button expand="block" :disabled="busy||(instructionsRequired&&!instructionsAcked)" @click="startRun(activeRun)">Confirm Pickup & Start Route</ion-button></div>
  <div v-else class="tracking-strip" :class="tracking.status.toLowerCase()"><div><b>GPS {{tracking.status}}</b><span v-if="tracking.last">Last update {{fmt(tracking.last.timestamp)}}</span><span v-else>Waiting for location</span></div><small>Tracking is tied to this active route.</small></div>

  <div class="stop-list"><div v-for="s in activeRun.stops" :key="s.id" :class="['route-stop',{current:s.id===nextStop?.id,done:s.status==='COMPLETED'}]"><div class="seq">{{s.sequence}}</div><div class="stop-body"><div class="stop-line"><b>{{s.name}}</b><span>{{s.status}}</span></div><small>{{s.type.replaceAll('_',' ')}} · {{s.deliveryWindow||s.address}}</small><div v-if="s.instructions?.length"><span v-for="(x,i) in s.instructions" :key="i" class="pillm" style="margin:2px">{{(typeof x==='string'?x:x.rule).replaceAll('_',' ')}}</span></div><div v-if="s.id===nextStop?.id && activeRun.status==='IN_PROGRESS'" class="stop-actions"><ion-button size="small" @click="nav(s,'google')">Navigate</ion-button><ion-button size="small" fill="outline" @click="nav(s,'waze')">Waze</ion-button><ion-button v-if="s.type==='DELIVERY'" size="small" color="success" @click="openSign(activeRun,s)">Receiver Sign-off</ion-button><ion-button v-else size="small" color="success" @click="completeStop(activeRun,s)">Complete {{s.type==='RETURN'?'Return':'Stop'}}</ion-button></div></div></div></div>
</div>
<div v-else class="schedule-empty">No active route assigned.</div>

<div v-if="signing" class="sign-overlay"><div class="sign-sheet"><div class="sign-head"><div><small>STOP {{signing.stop.sequence}} · PROOF OF DELIVERY</small><h2>{{signing.stop.name}}</h2><p>One receiver sign-off closes all deliveries linked to this stop.</p></div><button @click="signing=null">×</button></div><div class="pod-system-card"><b>{{signing.stop.name}}</b><span>Company, store, delivery reference and delivery details are filled by FlowDepot.</span><small v-if="signing.stop.podRecipientCount">Signed POD will be sent automatically to {{signing.stop.podRecipientCount}} registered receiving / manager contact{{signing.stop.podRecipientCount===1?'':'s'}}.</small><small v-else>No POD recipient is configured for this destination. The signed POD will still be stored in FlowDepot.</small></div><label>Receiver full name *</label><input v-model="receiverName" autocomplete="name"/><label>Remarks / exceptions</label><textarea v-model="remarks" rows="3" placeholder="Optional — only enter if there is a shortage, damage or other exception"></textarea><div class="signature-title"><label>Receiver signature *</label><button @click="clearSignature">Clear</button></div><canvas id="signature-pad" class="signature-pad" @pointerdown="start" @pointermove="move" @pointerup="end" @pointerleave="end"></canvas><small>Signature applies to the delivery records listed for this stop. Exceptions remain traceable in the audit record.</small><ion-button expand="block" color="success" :disabled="busy" @click="submitSignoff">Accept goods & complete stop</ion-button></div></div>
</ion-content></ion-page></template>
