<script setup>
import { computed,onMounted,ref } from 'vue'; import { api } from '../api'; import { IonPage,IonContent,IonSegment,IonSegmentButton,IonLabel } from '@ionic/vue';
const data=ref(null),view=ref('month'),selected=ref(new Date().toISOString().slice(0,10)); async function load(){data.value=(await api.get('/dashboard')).data} onMounted(load);
const runs=computed(()=>[...(data.value?.routeRuns||[])].sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt)));
const jobs=computed(()=>runs.value.length?runs.value:[...(data.value?.deliveries||[])].sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt)));
const selectedJobs=computed(()=>jobs.value.filter(d=>new Date(d.scheduledAt).toISOString().slice(0,10)===selected.value));
const monthDays=computed(()=>{const cur=new Date(selected.value+'T00:00:00'),y=cur.getFullYear(),m=cur.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),arr=[];for(let i=0;i<(first.getDay()+6)%7;i++)arr.push(null);for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;arr.push({d,date,count:jobs.value.filter(j=>new Date(j.scheduledAt).toISOString().slice(0,10)===date).length});}return arr});
const fmt=t=>new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),title=computed(()=>new Date(selected.value+'T00:00:00').toLocaleDateString([],{month:'long',year:'numeric'}));
function summary(j){return j.stops?`${j.totalStops} stops · standby ${j.standbyApproved?'approved':'pending'}`:`${j.fromId} → ${j.toId}`}
</script>
<template><ion-page><ion-content><div class="mob-hero"><small>MY WORK</small><h1>Schedule</h1><p>Routes may contain multiple pickups, deliveries and returns. Standby assignments are shown before dispatch.</p></div><div class="schedule-wrap"><ion-segment v-model="view"><ion-segment-button value="month"><ion-label>Calendar</ion-label></ion-segment-button><ion-segment-button value="list"><ion-label>List</ion-label></ion-segment-button></ion-segment><div v-if="view==='month'" class="calendar-card"><div class="calendar-title">{{title}}</div><div class="weekdays"><span v-for="d in ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']" :key="d">{{d}}</span></div><div class="calendar-grid"><button v-for="(x,i) in monthDays" :key="i" :disabled="!x" :class="['day',{selected:x?.date===selected,has:x?.count}]" @click="x&&(selected=x.date)"><span v-if="x">{{x.d}}</span><i v-if="x?.count">{{x.count}}</i></button></div></div><div class="day-jobs"><div class="day-head"><b>{{new Date(selected+'T00:00:00').toLocaleDateString([],{weekday:'long',day:'numeric',month:'long'})}}</b><span>{{selectedJobs.length}} route{{selectedJobs.length===1?'':'s'}}</span></div><div v-if="!selectedJobs.length" class="schedule-empty">No routes assigned.</div><div v-for="j in selectedJobs" :key="j.id" class="schedule-job"><div class="time">{{fmt(j.scheduledAt)}}</div><div><b>{{j.name||j.id}}</b><span>{{summary(j)}} · {{String(j.status).replaceAll('_',' ')}}</span><small v-if="j.standbyDriverName">Standby: {{j.standbyDriverName}}</small></div></div></div><div v-if="view==='list'" class="day-jobs"><div v-for="j in jobs" :key="j.id" class="schedule-job"><div class="time">{{new Date(j.scheduledAt).toLocaleDateString([],{day:'2-digit',month:'short'})}}<br>{{fmt(j.scheduledAt)}}</div><div><b>{{j.name||j.id}}</b><span>{{summary(j)}} · {{String(j.status).replaceAll('_',' ')}}</span><small v-if="j.standbyDriverName">Standby: {{j.standbyDriverName}} {{j.standbyApproved?'✓':''}}</small></div></div></div></div></ion-content></ion-page></template>
