<script setup>
import {computed,onMounted,ref} from 'vue';import {api} from '../api';
const data=ref({metrics:{},listings:[],bids:[],renewals:[],announcements:[],warehouses:[],pricingRules:[],rentalRates:[],applications:[]});
const showListing=ref(false),showAnnouncement=ref(false),showFee=ref(false),showRate=ref(false),showApplications=ref(false),mediaFor=ref(null),file=ref(null),busy=ref(false),reviewNote=ref('');
const listing=ref({warehouseId:'',title:'',description:'',availableSqft:1000,spaceType:'GENERAL',currency:'SGD',minimumBid:2000,bidStart:'',bidEnd:'',availableFrom:'',minTermMonths:12,published:true});
const ann=ref({title:'',message:'',priority:'NORMAL',audience:'ALL_TENANTS',endsAt:''});
const fee=ref({name:'',type:'FIXED_MONTHLY',amount:0,currency:'SGD',scope:'TENANT',effectiveFrom:'',active:true});
const rate=ref({warehouseId:'',spaceType:'GENERAL',ratePerSqft:0,currency:'SGD',billingCycle:'MONTHLY',minTermMonths:12,depositMonths:2,availableSqft:0,effectiveFrom:'',active:true});
function notify(title,message,type='success'){window.dispatchEvent(new CustomEvent('flowdepot:toast',{detail:{title,message,type}}))}
async function load(){data.value=(await api.get('/commercial/overview')).data;if(!listing.value.warehouseId)listing.value.warehouseId=data.value.warehouses?.[0]?.id||'';if(!rate.value.warehouseId)rate.value.warehouseId=data.value.warehouses?.[0]?.id||''}
const whName=id=>data.value.warehouses.find(w=>w.id===id)?.name||id;const tenantName=id=>data.value.tenants?.find(t=>t.id===id)?.name||id;
const pendingApps=computed(()=>data.value.applications.filter(a=>!['APPROVED','REJECTED'].includes(a.status)));
const money=(v,c='SGD')=>new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:2}).format(v||0);
async function run(fn,successTitle,successMessage,close){busy.value=true;try{await fn();if(close)close();notify(successTitle,successMessage);await load()}catch(e){notify('Action failed',e.response?.data?.error||e.message,'error')}finally{busy.value=false}}
function openFee(){fee.value={name:'',type:'FIXED_MONTHLY',amount:0,currency:'SGD',scope:'TENANT',effectiveFrom:new Date().toISOString().slice(0,10),active:true};showFee.value=true}
function openRate(){rate.value={warehouseId:data.value.warehouses?.[0]?.id||'',spaceType:'GENERAL',ratePerSqft:0,currency:'SGD',billingCycle:'MONTHLY',minTermMonths:12,depositMonths:2,availableSqft:0,effectiveFrom:new Date().toISOString().slice(0,10),active:true};showRate.value=true}
async function createFee(){if(!fee.value.name||Number(fee.value.amount)<0)return notify('Incomplete service charge','Enter a name and valid amount.','error');await run(()=>api.post('/pricing-rules',fee.value),'Service charge created',`${fee.value.name} is now active.`,()=>showFee.value=false)}
async function createRate(){if(!rate.value.warehouseId||Number(rate.value.ratePerSqft)<=0)return notify('Incomplete rental rate','Choose a warehouse and enter a rental rate.','error');await run(()=>api.post('/rental-rates',rate.value),'Rental rate saved',`${whName(rate.value.warehouseId)} rate card has been updated.`,()=>showRate.value=false)}
async function createListing(){if(!listing.value.warehouseId||!listing.value.title||!listing.value.bidStart||!listing.value.bidEnd)return notify('Listing incomplete','Warehouse, title and bidding dates are required.','error');await run(()=>api.post('/marketplace/listings',listing.value),'Warehouse space published',`${listing.value.title} is now available on the marketplace.`,()=>showListing.value=false)}
async function bidStatus(id,status){await run(()=>api.patch(`/leasing/bids/${id}/status`,{status}),status==='AWARDED'?'Bid awarded':'Bid rejected',`The bid status is now ${status.toLowerCase()}.`)}
async function renewalStatus(id,status){const note=window.prompt('Optional note to tenant:')||'';await run(()=>api.patch(`/leasing/renewals/${id}/status`,{status,ownerNote:note}),`Renewal ${status.toLowerCase()}`,`The tenant has been notified.`)}
async function applicationStatus(a,status){const note=reviewNote.value;await run(()=>api.patch(`/tenant-applications/${a.id}/status`,{status,note}),`Application ${status.toLowerCase()}`,`${a.companyName} has been moved to ${status.replaceAll('_',' ').toLowerCase()}.`);reviewNote.value=''}
async function publish(){if(!ann.value.title||!ann.value.message)return notify('Announcement incomplete','Enter a title and message.','error');await run(()=>api.post('/announcements',ann.value),'Announcement published','The announcement is now visible to tenants.',()=>showAnnouncement.value=false)}
async function uploadMedia(){if(!file.value)return notify('Choose a file','Select a warehouse photo or floor-plan image.','error');const f=new FormData();f.append('file',file.value);f.append('type','PHOTO');await run(()=>api.post(`/marketplace/listings/${mediaFor.value.id}/media`,f),'Media uploaded','The listing gallery has been updated.',()=>{mediaFor.value=null;file.value=null})}
onMounted(load);
</script>
<template><div>
<div class="hero"><div><h1>Rent, Bidding & Leasing</h1><p>Manage service charges, warehouse rental rates, tenant applications, space bidding, lease renewals and tenant communications.</p></div><div class="quick"><button class="btn" @click="showListing=true">Publish warehouse space</button><button class="btn secondary" @click="showAnnouncement=true">New announcement</button><a class="btn secondary" href="/spaces" target="_blank">Public marketplace</a></div></div>
<div class="grid4 section"><div class="card metric"><div class="label">MONTHLY RENT</div><div class="value">{{money(data.metrics.monthlyRent)}}</div></div><div class="card metric"><div class="label">PLATFORM MRR</div><div class="value">{{money(data.metrics.platformMrr)}}</div></div><div class="card metric"><div class="label">AVAILABLE SPACE</div><div class="value">{{Number(data.metrics.availableSqft||0).toLocaleString()}} sqft</div></div><div class="card metric"><div class="label">PENDING APPLICATIONS</div><div class="value">{{pendingApps.length}}</div></div></div>
<div class="management-grid section">
 <div class="card management-card"><div><span class="eyebrow-card">COMMERCIAL</span><h3>Platform service fees</h3><p>Subscription, per-delivery and transaction charges billed separately from rent and utilities.</p></div><button class="btn secondary" @click="openFee">New service charge</button></div>
 <div class="card management-card"><div><span class="eyebrow-card">LEASING</span><h3>Warehouse rental rate cards</h3><p>Set owner-controlled rates, available area, deposit and minimum lease terms by warehouse.</p></div><button class="btn secondary" @click="openRate">Set rental rate</button></div>
 <div class="card management-card"><div><span class="eyebrow-card">TENANT ONBOARDING</span><h3>New tenant applications</h3><p>{{pendingApps.length}} application(s) currently require review or a decision.</p></div><button class="btn secondary" @click="showApplications=true">Review applications</button></div>
</div>
<div class="split section">
 <div class="card table-wrap"><div class="table-title"><h3>Service charges</h3><span>Active commercial fees</span></div><table class="table"><thead><tr><th>Charge</th><th>Basis</th><th>Amount</th><th>Scope</th><th>Effective</th><th>Status</th></tr></thead><tbody><tr v-for="f in data.pricingRules" :key="f.id"><td><b>{{f.name}}</b></td><td>{{f.type.replaceAll('_',' ')}}</td><td>{{money(f.amount,f.currency)}}</td><td>{{f.scope}}</td><td>{{f.effectiveFrom}}</td><td><span class="pill" :class="f.active?'good':''">{{f.active?'ACTIVE':'INACTIVE'}}</span></td></tr></tbody></table></div>
 <div class="card table-wrap"><div class="table-title"><h3>Rental rates</h3><span>Owner-controlled warehouse rate cards</span></div><table class="table"><thead><tr><th>Warehouse</th><th>Type</th><th>Rate / sqft</th><th>Available</th><th>Term</th></tr></thead><tbody><tr v-for="r in data.rentalRates" :key="r.id"><td><b>{{whName(r.warehouseId)}}</b></td><td>{{r.spaceType.replaceAll('_',' ')}}</td><td>{{money(r.ratePerSqft,r.currency)}}</td><td>{{Number(r.availableSqft||0).toLocaleString()}} sqft</td><td>{{r.minTermMonths}} months</td></tr></tbody></table></div>
</div>
<div class="section card table-wrap"><div class="table-title"><div class="section-head"><div><h3>Warehouse space bidding</h3><span>Only spaces published by the owner appear on the public marketplace.</span></div></div></div><table class="table"><thead><tr><th>Space</th><th>Availability</th><th>Minimum bid</th><th>Bidding window</th><th>Media</th><th>Status</th></tr></thead><tbody><tr v-for="x in data.listings" :key="x.id"><td><b>{{x.title}}</b><br><small>{{whName(x.warehouseId)}} · {{Number(x.availableSqft).toLocaleString()}} sqft</small></td><td>{{new Date(x.availableFrom).toLocaleDateString()}}</td><td>{{money(x.minimumBid,x.currency)}}</td><td>{{new Date(x.bidStart).toLocaleDateString()}} → {{new Date(x.bidEnd).toLocaleDateString()}}</td><td>{{x.media?.length||0}} files <button class="mini-btn" @click="mediaFor=x">Add photo / plan</button></td><td><span class="pill">{{x.published?'PUBLISHED':'HIDDEN'}}</span></td></tr></tbody></table></div>
<div class="split section"><div class="card table-wrap"><div class="table-title"><h3>Submitted bids</h3><span>Owner makes the final award decision.</span></div><table class="table"><thead><tr><th>Bidder</th><th>Space</th><th>Bid</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="b in data.bids" :key="b.id"><td><b>{{b.companyName}}</b><br><small>{{b.email}}</small></td><td>{{data.listings.find(x=>x.id===b.listingId)?.title||'Warehouse listing'}}</td><td>{{money(b.amount,data.listings.find(x=>x.id===b.listingId)?.currency||'SGD')}}</td><td><span class="pill">{{b.status}}</span></td><td><button class="mini-btn" @click="bidStatus(b.id,'AWARDED')">Award</button> <button class="mini-btn" @click="bidStatus(b.id,'REJECTED')">Reject</button></td></tr></tbody></table></div><div class="card table-wrap"><div class="table-title"><h3>Lease renewal requests</h3><span>Tenant request → owner decision</span></div><table class="table"><thead><tr><th>Lease</th><th>Tenant</th><th>Term</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="r in data.renewals" :key="r.id"><td>{{r.leaseId}}</td><td>{{tenantName(r.tenantId)}}</td><td>{{r.requestedMonths}} months</td><td><span class="pill">{{r.status}}</span></td><td><button class="mini-btn" @click="renewalStatus(r.id,'APPROVED')">Approve</button> <button class="mini-btn" @click="renewalStatus(r.id,'REJECTED')">Reject</button></td></tr></tbody></table></div></div>
<div class="section card table-wrap"><div class="table-title"><h3>Tenant announcements</h3><span>Displayed to tenants after login and delivered as an in-app notification.</span></div><table class="table"><thead><tr><th>Title</th><th>Priority</th><th>Audience</th><th>Published</th><th>Expires</th></tr></thead><tbody><tr v-for="a in data.announcements" :key="a.id"><td><b>{{a.title}}</b><br><small>{{a.message}}</small></td><td><span class="pill">{{a.priority}}</span></td><td>{{a.audience.replaceAll('_',' ')}}</td><td>{{new Date(a.createdAt).toLocaleString()}}</td><td>{{a.endsAt?new Date(a.endsAt).toLocaleDateString():'No expiry'}}</td></tr></tbody></table></div>
<!-- Fee modal -->
<div v-if="showFee" class="modal-overlay" @click.self="showFee=false"><div class="card modal-dialog"><div class="section-head"><div><h3>New service charge</h3><span>Create a customer-facing service fee. This is separate from rent and utilities.</span></div><button class="mini-btn" @click="showFee=false">Close</button></div><div class="form-grid"><div class="field"><label>Charge name</label><input v-model="fee.name" placeholder="e.g. Platform subscription"></div><div class="field"><label>Charging basis</label><select v-model="fee.type"><option value="FIXED_MONTHLY">Fixed monthly</option><option value="PER_DELIVERY">Per delivery</option><option value="PER_EVENT">Per transaction/event</option></select></div><div class="field"><label>Amount</label><input type="number" min="0" step="0.01" v-model.number="fee.amount"></div><div class="field"><label>Currency</label><select v-model="fee.currency"><option>SGD</option><option>USD</option><option>EUR</option><option>GBP</option></select></div><div class="field"><label>Applies to</label><select v-model="fee.scope"><option value="TENANT">Each tenant/customer</option><option value="DELIVERY">Delivery</option><option value="ORGANIZATION">Organization</option></select></div><div class="field"><label>Effective from</label><input type="date" v-model="fee.effectiveFrom"></div></div><div class="modal-actions"><button class="btn secondary" @click="showFee=false">Cancel</button><button class="btn" :disabled="busy" @click="createFee">{{busy?'Saving…':'Create service charge'}}</button></div></div></div>
<!-- Rate modal -->
<div v-if="showRate" class="modal-overlay" @click.self="showRate=false"><div class="card modal-dialog"><div class="section-head"><div><h3>Set warehouse rental rate</h3><span>Choose the warehouse by name; FlowDepot stores the internal warehouse reference automatically.</span></div><button class="mini-btn" @click="showRate=false">Close</button></div><div class="form-grid"><div class="field"><label>Warehouse</label><select v-model="rate.warehouseId"><option v-for="w in data.warehouses" :key="w.id" :value="w.id">{{w.name}}</option></select></div><div class="field"><label>Space type</label><select v-model="rate.spaceType"><option value="GENERAL">General storage</option><option value="COLD_STORAGE">Cold storage</option><option value="FULFILMENT">Fulfilment</option><option value="HIGH_SECURITY">High security</option><option value="HAZMAT">Hazardous goods</option></select></div><div class="field"><label>Rate per sqft / month</label><input type="number" min="0" step="0.01" v-model.number="rate.ratePerSqft"></div><div class="field"><label>Available area (sqft)</label><input type="number" min="0" v-model.number="rate.availableSqft"></div><div class="field"><label>Minimum term</label><input type="number" min="1" v-model.number="rate.minTermMonths"></div><div class="field"><label>Deposit (months)</label><input type="number" min="0" v-model.number="rate.depositMonths"></div><div class="field"><label>Currency</label><select v-model="rate.currency"><option>SGD</option><option>USD</option></select></div><div class="field"><label>Effective from</label><input type="date" v-model="rate.effectiveFrom"></div></div><div class="modal-actions"><button class="btn secondary" @click="showRate=false">Cancel</button><button class="btn" :disabled="busy" @click="createRate">{{busy?'Saving…':'Save rental rate'}}</button></div></div></div>
<!-- Applications -->
<div v-if="showApplications" class="modal-overlay" @click.self="showApplications=false"><div class="card modal-dialog modal-lg"><div class="section-head"><div><h3>Tenant applications</h3><span>Review applicants using company and warehouse names instead of internal IDs.</span></div><button class="mini-btn" @click="showApplications=false">Close</button></div><div v-if="!data.applications.length" class="empty">No tenant applications.</div><div v-for="a in data.applications" :key="a.id" class="application-card"><div class="section-head"><div><h3>{{a.companyName}}</h3><span>{{a.contactName}} · {{a.email}}</span></div><span class="pill">{{a.status.replaceAll('_',' ')}}</span></div><div class="application-facts"><span><b>Preferred warehouse</b>{{whName(a.requestedWarehouseId)}}</span><span><b>Required space</b>{{Number(a.requestedSqft||0).toLocaleString()}} sqft</span><span><b>Term</b>{{a.termMonths}} months</span><span><b>Start</b>{{new Date(a.requestedStart).toLocaleDateString()}}</span></div><p>{{a.notes||'No special requirements provided.'}}</p><div><span v-for="h in a.cargoProfile||[]" :key="h" class="handling-chip selected">{{h.replaceAll('_',' ')}}</span></div><div v-if="!['APPROVED','REJECTED'].includes(a.status)" class="application-actions"><button class="btn secondary" @click="applicationStatus(a,'UNDER_REVIEW')">Mark under review</button><button class="btn" @click="applicationStatus(a,'APPROVED')">Approve</button><button class="mini-btn danger-lite" @click="applicationStatus(a,'REJECTED')">Reject</button></div></div></div></div>
<!-- other modals -->
<div v-if="showListing" class="modal-overlay" @click.self="showListing=false"><div class="card modal-dialog"><div class="section-head"><div><h3>Publish warehouse space</h3><span>Configure availability and a controlled bidding window.</span></div><button class="mini-btn" @click="showListing=false">Close</button></div><div class="form-grid section"><div class="field"><label>Warehouse</label><select v-model="listing.warehouseId"><option v-for="w in data.warehouses" :value="w.id" :key="w.id">{{w.name}}</option></select></div><div class="field"><label>Listing title</label><input v-model="listing.title"></div><div class="field"><label>Available sqft</label><input type="number" v-model.number="listing.availableSqft"></div><div class="field"><label>Space type</label><select v-model="listing.spaceType"><option value="GENERAL">General storage</option><option value="COLD_STORAGE">Cold storage</option><option value="FULFILMENT">Fulfilment</option><option value="HIGH_SECURITY">High security</option><option value="HAZMAT">Hazardous goods</option></select></div><div class="field"><label>Minimum bid</label><input type="number" v-model.number="listing.minimumBid"></div><div class="field"><label>Currency</label><select v-model="listing.currency"><option>SGD</option><option>USD</option></select></div><div class="field"><label>Bidding starts</label><input type="datetime-local" v-model="listing.bidStart"></div><div class="field"><label>Bidding ends</label><input type="datetime-local" v-model="listing.bidEnd"></div><div class="field"><label>Space available from</label><input type="date" v-model="listing.availableFrom"></div><div class="field"><label>Minimum term (months)</label><input type="number" v-model.number="listing.minTermMonths"></div></div><div class="field"><label>Description</label><textarea rows="5" v-model="listing.description"></textarea></div><div class="modal-actions"><button class="btn secondary" @click="showListing=false">Cancel</button><button class="btn" :disabled="busy" @click="createListing">{{busy?'Publishing…':'Publish listing'}}</button></div></div></div>
<div v-if="showAnnouncement" class="modal-overlay" @click.self="showAnnouncement=false"><div class="card modal-dialog"><div class="section-head"><h3>Publish tenant announcement</h3><button class="mini-btn" @click="showAnnouncement=false">Close</button></div><div class="field section"><label>Title</label><input v-model="ann.title"></div><div class="field section"><label>Message</label><textarea rows="5" v-model="ann.message"></textarea></div><div class="form-grid section"><div class="field"><label>Priority</label><select v-model="ann.priority"><option>NORMAL</option><option>IMPORTANT</option><option>URGENT</option></select></div><div class="field"><label>Visible until</label><input type="datetime-local" v-model="ann.endsAt"></div></div><div class="modal-actions"><button class="btn secondary" @click="showAnnouncement=false">Cancel</button><button class="btn" :disabled="busy" @click="publish">{{busy?'Publishing…':'Publish to all tenants'}}</button></div></div></div>
<div v-if="mediaFor" class="modal-overlay" @click.self="mediaFor=null"><div class="card modal-dialog"><div class="section-head"><div><h3>Add listing media</h3><span>{{mediaFor.title}}</span></div><button class="mini-btn" @click="mediaFor=null">Close</button></div><div class="callout section">Upload warehouse photos, floor-plan images or rendered layouts. These appear on the public listing.</div><div class="field section"><label>Image / floor plan</label><input type="file" accept="image/*" @change="file=$event.target.files[0]"></div><div class="modal-actions"><button class="btn secondary" @click="mediaFor=null">Cancel</button><button class="btn" :disabled="busy" @click="uploadMedia">{{busy?'Uploading…':'Upload'}}</button></div></div></div>
</div></template>
