<script setup>
import { onMounted,ref,computed } from 'vue';import { api,API_BASE } from '../api';import { useAuthStore } from '../stores/auth';
const rows=ref([]),runs=ref([]),availability=ref([]),dispatch=ref({drivers:[],vehicles:[]}),auth=useAuthStore(),editing=ref(null),selected=ref(null),qrUrl=ref('');
const canDispatch=computed(()=>['OWNER','WAREHOUSE_MANAGER'].includes(auth.user?.role));const fmt=t=>t?new Date(t).toLocaleString():'-';
async function load(){rows.value=(await api.get('/deliveries')).data;runs.value=(await api.get('/route-runs')).data;if(canDispatch.value){dispatch.value=(await api.get('/dispatch/options')).data;availability.value=(await api.get('/driver/availability')).data}}onMounted(load);
const driver=id=>dispatch.value.drivers.find(x=>x.id===id)?.name||id||'Unassigned',vehicle=id=>dispatch.value.vehicles.find(x=>x.id===id)?.plate||id||'Unassigned';
function edit(run){editing.value={run,primaryDriverId:run.primaryDriverId||'',standbyDriverId:run.standbyDriverId||'',vehicleId:run.vehicleId||'',approveStandby:run.standbyApproved||false}}
async function save(){await api.patch(`/route-runs/${editing.value.run.id}/dispatch`,{primaryDriverId:editing.value.primaryDriverId,standbyDriverId:editing.value.standbyDriverId,vehicleId:editing.value.vehicleId,approveStandby:editing.value.approveStandby});editing.value=null;await load()}
async function activate(run){if(!confirm(`Activate approved standby driver for ${run.id}?`))return;await api.post(`/route-runs/${run.id}/activate-standby`);await load()}
async function reviewAvailability(r,status){const note=prompt(`Optional note for ${status.toLowerCase()}:`,'')||'';await api.patch(`/driver/availability/${r.id}/status`,{status,reviewNote:note});await load()}
function qr(d,action){selected.value=d;qrUrl.value=`${API_BASE}/qr/DELIVERY/${d.id}?action=${action}`}
function trackingClass(r){return r.trackingStatus==='LIVE'?'good':r.trackingStatus==='STALE'?'warn':''}
</script>
<template>
<div class="section-head"><div><h3>Routes, deliveries & dispatch</h3><span>One route can contain multiple pickups, destinations, returns and delivery records. Driver interaction stays minimal while FlowDepot records the route.</span></div><button class="btn secondary" @click="load">Refresh</button></div>

<div class="route-grid">
  <div v-for="r in runs" :key="r.id" class="card route-card-web">
    <div class="section-head"><div><h3>{{r.name}}</h3><span>{{r.id}} · {{fmt(r.scheduledAt)}}</span></div><span class="pill" :class="r.status==='COMPLETED'?'good':''">{{r.status.replaceAll('_',' ')}}</span></div>
    <div class="route-kpis"><div><small>Active driver</small><b>{{r.activeDriverName||'Unassigned'}}</b></div><div><small>Standby</small><b>{{r.standbyDriverName||'Not set'}}</b><span>{{r.standbyApproved?'✓ Approved':'Approval required'}}</span></div><div><small>Vehicle</small><b>{{r.vehiclePlate||'Unassigned'}}</b></div><div><small>GPS</small><b><span class="pill" :class="trackingClass(r)">{{r.trackingStatus}}</span></b><span v-if="r.lastLocation">{{fmt(r.lastLocation.timestamp)}}</span></div></div>
    <div class="route-progress"><b>{{r.completedStops}} / {{r.totalStops}} stops</b><div><i :style="{width:`${Math.round((r.completedStops/Math.max(1,r.totalStops))*100)}%`}"></i></div></div>
    <div class="route-stops-web"><div v-for="s in r.stops" :key="s.id" :class="['route-stop-web',{done:s.status==='COMPLETED',current:s.id===r.nextStopId}]"><span>{{s.sequence}}</span><div><b>{{s.name}}</b><small>{{s.type}} · {{s.deliveryWindow||s.address}}</small></div><em>{{s.status}}</em></div></div>
    <div class="actions-row" v-if="canDispatch"><button class="btn" @click="edit(r)">Dispatch plan</button><button v-if="r.standbyApproved&&r.activeDriverId!==r.standbyDriverId&&['ASSIGNED','IN_PROGRESS'].includes(r.status)" class="btn secondary" @click="activate(r)">Activate standby</button></div>
  </div>
</div>

<div v-if="canDispatch" class="section-head section"><div><h3>Driver availability & medical leave</h3><span>Review leave / MC submissions before activating a standby driver. Approval of leave does not silently rewrite the route.</span></div></div>
<div v-if="canDispatch" class="card table-wrap"><table class="table"><thead><tr><th>Driver</th><th>Type</th><th>Period</th><th>Status</th><th>Supporting file</th><th>Review</th></tr></thead><tbody><tr v-for="r in availability" :key="r.id"><td>{{driver(r.driverId)}}</td><td>{{r.type.replaceAll('_',' ')}}</td><td>{{r.start}} → {{r.end||r.start}}</td><td><span class="pill" :class="r.status==='APPROVED'?'good':r.status==='REJECTED'?'warn':''">{{r.status}}</span></td><td><a v-if="r.documentPath" :href="`${API_BASE.replace('/api','')}${r.documentPath}`" target="_blank">View document</a><span v-else>—</span></td><td><div style="display:flex;gap:6px"><button v-if="r.status==='SUBMITTED'" class="btn" @click="reviewAvailability(r,'APPROVED')">Approve</button><button v-if="r.status==='SUBMITTED'" class="btn secondary" @click="reviewAvailability(r,'REJECTED')">Reject</button></div></td></tr></tbody></table></div>

<div class="section-head section"><div><h3>Individual delivery records</h3><span>Each customer delivery remains separate for POD, billing, tenant visibility and audit.</span></div></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Delivery</th><th>Route / stop</th><th>From / To</th><th>Driver</th><th>Status</th><th>Evidence</th></tr></thead><tbody><tr v-for="d in rows" :key="d.id"><td><b>{{d.id}}</b><br><small>{{d.type}}</small></td><td>{{d.routeRunId||'Point-to-point'}}<br><small>{{d.routeStopId||'-'}}</small></td><td>{{d.fromId}} → {{d.toId}}</td><td>{{driver(d.driverId)}}<br><small v-if="d.standbyDriverId">Standby: {{driver(d.standbyDriverId)}}</small></td><td><span class="pill" :class="d.status==='DELIVERED'?'good':''">{{d.status.replaceAll('_',' ')}}</span></td><td><button class="btn secondary" @click="qr(d,'PICKUP')">QR</button><span v-if="d.receiverSignoff" class="evidence-ok">✓ Signed POD</span></td></tr></tbody></table></div>

<div v-if="editing" class="modal-overlay" @click.self="editing=null"><div class="card modal-dialog"><div class="section-head"><div><h3>Dispatch {{editing.run.id}}</h3><span>Primary driver, approved standby driver and vehicle are fixed before route start.</span></div><button class="mini-btn" @click="editing=null">Close</button></div><div class="form-grid"><div class="field"><label>Primary driver</label><select v-model="editing.primaryDriverId"><option value="">Select</option><option v-for="d in dispatch.drivers" :key="d.id" :value="d.id">{{d.name}} · {{d.status}} · score {{d.score}}</option></select></div><div class="field"><label>Standby driver</label><select v-model="editing.standbyDriverId"><option value="">Select</option><option v-for="d in dispatch.drivers" :key="d.id" :value="d.id" :disabled="d.id===editing.primaryDriverId">{{d.name}} · {{d.status}}</option></select></div><div class="field"><label>Vehicle</label><select v-model="editing.vehicleId"><option value="">Select</option><option v-for="v in dispatch.vehicles" :key="v.id" :value="v.id" :disabled="v.status!=='AVAILABLE'">{{v.plate}} · {{v.capacityKg}} kg</option></select></div><div class="field check-field"><label><input type="checkbox" v-model="editing.approveStandby"/> Approve standby assignment</label><small>The route cannot start when company policy requires a standby and approval is missing.</small></div></div><button class="btn section" @click="save">Save dispatch plan</button></div></div>
<div v-if="selected" class="card section modal-card"><div class="section-head"><div><h3>QR handoff · {{selected.id}}</h3><span>Optional scan evidence for cargo verification.</span></div><button class="btn secondary" @click="selected=null">Close</button></div><div class="split"><div class="qrbox"><img :src="qrUrl" style="max-width:260px;width:100%"/></div><div><p style="font-size:13px;line-height:1.7;color:#64748b">Multi-stop routes do not require the driver to press through every operational state. Scan/verify at pickup, then one route-start confirmation places linked deliveries in transit.</p></div></div></div>
</template>
