<script setup>
import {onMounted,ref} from 'vue';import {api} from '../api';
const data=ref({leases:[],renewals:[],announcements:[]}),renew=ref(null),form=ref({requestedMonths:12,notes:''}),busy=ref(false);
function notify(title,message,type='success'){window.dispatchEvent(new CustomEvent('flowdepot:toast',{detail:{title,message,type}}))}
async function load(){data.value=(await api.get('/leasing/my')).data}
async function submit(){busy.value=true;try{const lease=renew.value;const r=await api.post('/leasing/renewals',{leaseId:lease.id,...form.value});renew.value=null;form.value={requestedMonths:12,notes:''};notify('Renewal request submitted',`${r.data.requestedMonths}-month renewal sent to the warehouse owner for review.`);await load()}catch(e){notify('Unable to submit renewal',e.response?.data?.error||'Please review the request and try again.','error')}finally{busy.value=false}}
onMounted(load);
</script>
<template><div><div class="hero"><div><h1>My Lease & Announcements</h1><p>Review your current warehouse leases, request renewals and read important notices from the warehouse owner.</p></div><a class="btn secondary" href="/spaces">Browse available spaces</a></div>
<div v-if="data.announcements.length" class="section"><div class="section-head"><div><h3>Owner announcements</h3><span>Notices published to tenants</span></div></div><div class="announcement-list"><div v-for="a in data.announcements" :key="a.id" class="card announcement"><span class="pill" :class="a.priority==='URGENT'?'bad':a.priority==='IMPORTANT'?'warn':''">{{a.priority}}</span><div><h3>{{a.title}}</h3><p>{{a.message}}</p><small>Published {{new Date(a.createdAt).toLocaleString()}} by {{a.createdBy}}</small></div></div></div></div>
<div class="section card table-wrap"><div class="table-title"><div class="section-head"><div><h3>My lease agreements</h3><span>Renewals require owner approval</span></div></div></div><table class="table"><thead><tr><th>Lease</th><th>Warehouse</th><th>Area</th><th>Monthly rent</th><th>Expiry</th><th></th></tr></thead><tbody><tr v-for="l in data.leases" :key="l.id"><td><b>{{l.id}}</b></td><td>{{l.warehouseName||l.warehouseId}}</td><td>{{Number(l.areaSqft).toLocaleString()}} sqft</td><td>{{l.currency}} {{Number(l.monthlyRent).toLocaleString()}}</td><td>{{new Date(l.end).toLocaleDateString()}}</td><td><button class="mini-btn" :disabled="data.renewals.some(r=>r.leaseId===l.id&&['SUBMITTED','UNDER_REVIEW'].includes(r.status))" @click="renew=l">{{data.renewals.some(r=>r.leaseId===l.id&&['SUBMITTED','UNDER_REVIEW'].includes(r.status))?'Renewal pending':'Request renewal'}}</button></td></tr></tbody></table></div>
<div class="section card table-wrap"><div class="table-title"><h3>Renewal requests</h3></div><table class="table"><thead><tr><th>Lease</th><th>Requested term</th><th>Submitted</th><th>Status</th><th>Owner note</th></tr></thead><tbody><tr v-for="r in data.renewals" :key="r.id"><td>{{r.leaseId}}</td><td>{{r.requestedMonths}} months</td><td>{{new Date(r.submittedAt).toLocaleDateString()}}</td><td><span class="pill">{{r.status}}</span></td><td>{{r.ownerNote||'—'}}</td></tr></tbody></table></div>
<div v-if="renew" class="modal-overlay" @click.self="renew=null"><div class="card modal-dialog"><div class="section-head"><div><h3>Request lease renewal</h3><span>Expires {{new Date(renew.end).toLocaleDateString()}}</span></div><button class="mini-btn" @click="renew=null">Close</button></div><div class="field section"><label>Requested extension</label><select v-model.number="form.requestedMonths"><option :value="6">6 months</option><option :value="12">12 months</option><option :value="24">24 months</option><option :value="36">36 months</option></select></div><div class="field section"><label>Message to owner</label><textarea rows="5" v-model="form.notes" placeholder="Explain any renewal requirements, requested changes or timing constraints…"></textarea></div><div class="modal-actions"><button class="btn secondary" @click="renew=null">Cancel</button><button class="btn" :disabled="busy" @click="submit">{{busy?'Submitting…':'Submit for owner approval'}}</button></div></div></div>
</div></template>
