<script setup>
import {computed,onMounted,ref,watch} from 'vue';
import {api} from '../api';
import {useAuthStore} from '../stores/auth';
const auth=useAuthStore();
const data=ref({unplanned:[],routeRuns:[],drivers:[],vehicles:[],goodsRequests:[],deliveryRequests:[],warehouses:[],stores:[],tenants:[],inventory:[]});
const ops=ref({deliveryRequests:[],warehouses:[],stores:[],tenants:[],inventory:[]});
const selected=ref([]),showAdhoc=ref(false),showPlan=ref(false),busy=ref(false);
const handlingOptions=['FRAGILE','KEEP_UPRIGHT','DO_NOT_STACK','KEEP_DRY','TEMPERATURE_CONTROLLED','HIGH_VALUE','HEAVY','OVERSIZED','MEDICAL','FOOD'];
const adhoc=ref({tenantId:'',pickupId:'',destinationMode:'SAVED',stopId:'',building:'',street:'',unit:'',postalCode:'',country:'Singapore',loadingBay:'',contactName:'',contactPhone:'',sku:'',qty:1,specialHandling:[],requestedDate:'',requestedTimeWindow:'ANYTIME',instructions:'',notes:''});
const plan=ref({scheduledAt:'',primaryDriverId:'',standbyDriverId:'',vehicleId:'',name:'',managerNote:''});
const manager=computed(()=>['OWNER','WAREHOUSE_MANAGER'].includes(auth.user?.role));
const refData=computed(()=>manager.value?data.value:ops.value);
const tenantId=computed(()=>auth.user?.role==='TENANT'?auth.user.tenantId:adhoc.value.tenantId);
const stores=computed(()=>refData.value.stores?.filter(s=>!tenantId.value||s.tenantId===tenantId.value)||[]);
const inventoryOptions=computed(()=>refData.value.inventory?.filter(i=>!tenantId.value||i.tenantId===tenantId.value).filter(i=>i.locationType==='WAREHOUSE'&&(!adhoc.value.pickupId||i.locationId===adhoc.value.pickupId))||[]);
const uniqueItems=computed(()=>{const m=new Map();for(const i of inventoryOptions.value){if(!m.has(i.sku))m.set(i.sku,i)}return [...m.values()]});
const pickup=computed(()=>refData.value.warehouses?.find(w=>w.id===adhoc.value.pickupId));
const selectedStore=computed(()=>stores.value.find(s=>s.id===adhoc.value.stopId));
const selectedItem=computed(()=>uniqueItems.value.find(i=>i.sku===adhoc.value.sku));
function notify(title,message,type='success'){window.dispatchEvent(new CustomEvent('flowdepot:toast',{detail:{title,message,type}}))}
function friendlyHandling(v){return v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}
function toggleHandling(v){const a=adhoc.value.specialHandling;const idx=a.indexOf(v);idx>=0?a.splice(idx,1):a.push(v)}
function formatDestination(){return [adhoc.value.building,adhoc.value.street,adhoc.value.unit,adhoc.value.postalCode,adhoc.value.country].filter(Boolean).join(', ')}
function resetAdhoc(){adhoc.value={tenantId:auth.user?.role==='TENANT'?auth.user.tenantId:'',pickupId:refData.value.warehouses?.[0]?.id||'',destinationMode:'SAVED',stopId:'',building:'',street:'',unit:'',postalCode:'',country:'Singapore',loadingBay:'',contactName:'',contactPhone:'',sku:'',qty:1,specialHandling:[],requestedDate:'',requestedTimeWindow:'ANYTIME',instructions:'',notes:''}}
async function load(){if(manager.value){data.value=(await api.get('/dispatch/planning')).data}else{ops.value=(await api.get('/operations/overview')).data}if(!adhoc.value.pickupId)resetAdhoc()}
onMounted(load);
watch(()=>adhoc.value.tenantId,()=>{adhoc.value.stopId='';adhoc.value.sku=''});
watch(()=>adhoc.value.pickupId,()=>{if(!inventoryOptions.value.some(i=>i.sku===adhoc.value.sku))adhoc.value.sku=''});
watch(()=>adhoc.value.stopId,(id)=>{const s=stores.value.find(x=>x.id===id);if(s){adhoc.value.building=s.name||'';adhoc.value.street=s.address||'';adhoc.value.loadingBay=s.deliveryEntrance||'';adhoc.value.instructions=s.accessNotes||''}});
watch(()=>adhoc.value.sku,(sku)=>{const i=uniqueItems.value.find(x=>x.sku===sku);if(i){for(const h of i.handlingRules||[])if(!adhoc.value.specialHandling.includes(h))adhoc.value.specialHandling.push(h)}});
function openAdhoc(){resetAdhoc();showAdhoc.value=true}
async function requestAdhoc(){
 if(manager.value&&!adhoc.value.tenantId)return notify('Customer required','Choose the customer/tenant this request belongs to.','error');
 if(!adhoc.value.pickupId)return notify('Pickup required','Choose a pickup warehouse.','error');
 if(!adhoc.value.sku||Number(adhoc.value.qty)<1)return notify('Goods required','Choose an item and enter a valid quantity.','error');
 if(adhoc.value.destinationMode==='SAVED'&&!adhoc.value.stopId)return notify('Destination required','Choose a saved destination.','error');
 if(adhoc.value.destinationMode==='CUSTOM'&&(!adhoc.value.street||!adhoc.value.postalCode))return notify('Address incomplete','Street address and postal code are required for a one-time destination.','error');
 busy.value=true;
 try{
   const destinationAddress=formatDestination()||(selectedStore.value?.address||'');
   const stop={type:adhoc.value.destinationMode==='SAVED'?'STORE':'EXTERNAL',id:adhoc.value.destinationMode==='SAVED'?adhoc.value.stopId:undefined,address:destinationAddress,building:adhoc.value.building,street:adhoc.value.street,unit:adhoc.value.unit,postalCode:adhoc.value.postalCode,country:adhoc.value.country,loadingBay:adhoc.value.loadingBay,contactName:adhoc.value.contactName,contactPhone:adhoc.value.contactPhone,instructions:[adhoc.value.instructions].filter(Boolean),items:[{sku:adhoc.value.sku,qty:Number(adhoc.value.qty)}]};
   const payload={requestType:'AD_HOC',tenantId:manager.value?adhoc.value.tenantId:undefined,pickup:{type:'WAREHOUSE',id:adhoc.value.pickupId,address:pickup.value?.address||''},stops:[stop],items:[{sku:adhoc.value.sku,qty:Number(adhoc.value.qty)}],specialHandling:adhoc.value.specialHandling,notes:adhoc.value.notes,requestedWindow:adhoc.value.requestedDate?{start:`${adhoc.value.requestedDate}T00:00:00`,label:adhoc.value.requestedTimeWindow}:null};
   const r=await api.post('/delivery-requests',payload);showAdhoc.value=false;notify('Delivery request submitted',`${r.data.id} has been sent to warehouse management for review.`);await load();
 }catch(e){notify('Unable to submit',e.response?.data?.error||e.message,'error')}finally{busy.value=false}
}
async function review(r,status){try{await api.patch(`/delivery-requests/${r.id}/review`,{status});notify(`Request ${status.toLowerCase()}`,`${r.id} was ${status.toLowerCase()}.`);await load()}catch(e){notify('Action failed',e.response?.data?.error||e.message,'error')}}
async function convert(r){try{await api.post(`/delivery-requests/${r.id}/plan`,{});notify('Delivery records created',`${r.id} is now ready for route planning.`);await load()}catch(e){notify('Action failed',e.response?.data?.error||e.message,'error')}}
function toggle(id){selected.value=selected.value.includes(id)?selected.value.filter(x=>x!==id):[...selected.value,id]}
async function createRoute(){busy.value=true;try{await api.post('/dispatch/plan-route',{...plan.value,deliveryIds:selected.value});selected.value=[];showPlan.value=false;notify('Route created','The driver, standby driver and vehicle schedule has been saved.');await load()}catch(e){notify('Unable to create route',e.response?.data?.error||e.message,'error')}finally{busy.value=false}}
const tenantName=id=>refData.value.tenants?.find(t=>t.id===id)?.name||'Customer';
const locationName=(type,id,address)=> type==='STORE'?(refData.value.stores?.find(s=>s.id===id)?.name||address||'Saved destination'):(refData.value.warehouses?.find(w=>w.id===id)?.name||address||'Location');
const itemName=sku=>refData.value.inventory?.find(i=>i.sku===sku)?.name||sku;
</script>
<template>
<div class="section-head"><div><h3>Delivery planning & driver schedule</h3><span>Customer requests enter a planning queue. Warehouse managers consolidate deliveries into controlled multi-stop routes and assign available drivers, standby coverage and vehicles.</span></div><button class="btn" @click="openAdhoc">+ Ad-hoc delivery request</button></div>
<template v-if="manager">
<div class="section-head section"><div><h3>Customer delivery requests</h3><span>Approve or reject before they become operational delivery records.</span></div></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Request</th><th>Customer</th><th>Pickup</th><th>Destination(s)</th><th>Goods</th><th>Handling</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="r in data.deliveryRequests" :key="r.id"><td><b>{{r.id}}</b><br><small>{{r.requestType.replaceAll('_',' ')}}</small></td><td>{{tenantName(r.tenantId)}}</td><td>{{locationName(r.pickup?.type,r.pickup?.id,r.pickup?.address)}}</td><td><span v-for="s in r.stops" :key="s.id||s.address"><b>{{locationName(s.type,s.id,s.address)}}</b><br><small>{{s.unit?`${s.unit} · `:''}}{{s.postalCode||''}}</small><br></span></td><td><span v-for="x in r.items||[]" :key="x.sku">{{itemName(x.sku)}} × {{x.qty}}<br></span></td><td><span v-for="h in r.specialHandling||[]" :key="h" class="pill warn" style="margin:2px">{{friendlyHandling(h)}}</span></td><td><span class="pill">{{r.status}}</span></td><td><div class="actions-row"><button v-if="r.status==='REQUESTED'" class="btn" @click="review(r,'APPROVED')">Approve</button><button v-if="r.status==='REQUESTED'" class="btn secondary" @click="review(r,'REJECTED')">Reject</button><button v-if="r.status==='APPROVED'" class="btn" @click="convert(r)">Create delivery records</button></div></td></tr></tbody></table></div>
<div class="section-head section"><div><h3>Planning queue</h3><span>Select one or more compatible deliveries and create a multi-stop run.</span></div><button class="btn" :disabled="!selected.length" @click="showPlan=true">Plan selected ({{selected.length}})</button></div>
<div class="route-grid"><div v-for="d in data.unplanned" :key="d.id" class="card route-card-web" :style="selected.includes(d.id)?'outline:2px solid #0b6fb7':''"><div class="section-head"><div><h3>{{d.id}}</h3><span>{{locationName(d.fromType,d.fromId,d.fromId)}} → {{locationName(d.toType,d.toId,d.toId)}}</span></div><input type="checkbox" :checked="selected.includes(d.id)" @change="toggle(d.id)"/></div><p><b>{{(d.items||[]).reduce((a,x)=>a+Number(x.qty||0),0)}} units</b> · {{d.priority}}</p><div><span v-for="x in d.instructions||[]" :key="x.sku+x.rule" class="pill warn" style="margin:2px">{{friendlyHandling(x.rule)}}</span></div></div></div>
<div class="section-head section"><div><h3>Driver & vehicle schedule</h3><span>Existing routes are visible before new assignments are made. Server-side conflict checks block overlapping assignments.</span></div></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Run</th><th>Scheduled</th><th>Primary</th><th>Standby</th><th>Vehicle</th><th>Stops</th><th>Status</th></tr></thead><tbody><tr v-for="r in data.routeRuns" :key="r.id"><td><b>{{r.name}}</b><br><small>{{r.id}}</small></td><td>{{new Date(r.scheduledAt).toLocaleString()}}</td><td>{{r.primaryDriverName}}</td><td>{{r.standbyDriverName||'-'}}</td><td>{{r.vehiclePlate}}</td><td>{{r.completedStops}} / {{r.totalStops}}</td><td><span class="pill">{{r.status}}</span></td></tr></tbody></table></div>
</template>
<template v-else><div class="section-head section"><div><h3>My delivery requests</h3><span>Track ad-hoc delivery requests submitted to the warehouse team.</span></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>Request</th><th>Pickup</th><th>Destination</th><th>Status</th></tr></thead><tbody><tr v-for="r in ops.deliveryRequests" :key="r.id"><td><b>{{r.id}}</b></td><td>{{locationName(r.pickup?.type,r.pickup?.id,r.pickup?.address)}}</td><td>{{r.stops?.map(s=>locationName(s.type,s.id,s.address)).join(', ')}}</td><td><span class="pill">{{r.status}}</span></td></tr></tbody></table></div></template>
<div v-if="showAdhoc" class="modal-overlay" @click.self="showAdhoc=false"><div class="card modal-dialog modal-lg"><div class="section-head"><div><h3>Ad-hoc delivery request</h3><span>Use names and saved locations. FlowDepot keeps internal IDs in the background.</span></div><button class="mini-btn" @click="showAdhoc=false">Close</button></div>
<div class="form-section" v-if="manager"><h4>Customer</h4><div class="field"><label>Customer / tenant</label><select v-model="adhoc.tenantId"><option value="">Choose customer</option><option v-for="t in data.tenants" :key="t.id" :value="t.id">{{t.name}}</option></select></div></div>
<div class="form-section"><h4>1. Pickup</h4><div class="field"><label>Pickup warehouse</label><select v-model="adhoc.pickupId"><option value="">Choose warehouse</option><option v-for="w in refData.warehouses" :key="w.id" :value="w.id">{{w.name}} — {{w.address}}</option></select></div><div v-if="pickup" class="selected-summary"><b>{{pickup.name}}</b><span>{{pickup.address}}</span></div></div>
<div class="form-section"><h4>2. Destination</h4><div class="choice-row"><button type="button" :class="['choice-chip',{selected:adhoc.destinationMode==='SAVED'}]" @click="adhoc.destinationMode='SAVED'">Saved store / location</button><button type="button" :class="['choice-chip',{selected:adhoc.destinationMode==='CUSTOM'}]" @click="adhoc.destinationMode='CUSTOM';adhoc.stopId=''">One-time address</button></div><div v-if="adhoc.destinationMode==='SAVED'" class="field section-sm"><label>Destination</label><select v-model="adhoc.stopId"><option value="">Choose destination</option><option v-for="s in stores" :key="s.id" :value="s.id">{{s.name}} — {{s.address}}</option></select></div><div class="form-grid section-sm"><div class="field"><label>Building / mall / location</label><input v-model="adhoc.building" placeholder="e.g. Velocity @ Novena Square"></div><div class="field"><label>Street address *</label><input v-model="adhoc.street" placeholder="e.g. 238 Thomson Road"></div><div class="field"><label>Unit / suite</label><input v-model="adhoc.unit" placeholder="#03-25"></div><div class="field"><label>Postal code *</label><input v-model="adhoc.postalCode" inputmode="numeric" placeholder="307683"></div><div class="field"><label>Loading bay / service entrance</label><input v-model="adhoc.loadingBay" placeholder="Loading Bay B"></div><div class="field"><label>Country</label><input v-model="adhoc.country"></div><div class="field"><label>Delivery contact</label><input v-model="adhoc.contactName" placeholder="Store manager / receiving team"></div><div class="field"><label>Contact number</label><input v-model="adhoc.contactPhone" placeholder="+65 …"></div></div></div>
<div class="form-section"><h4>3. Goods</h4><div class="form-grid"><div class="field"><label>Product / item</label><select v-model="adhoc.sku"><option value="">Choose product</option><option v-for="i in uniqueItems" :key="i.sku" :value="i.sku">{{i.name}} — {{i.sku}} · {{i.availableQty??i.qty}} {{i.uom||'units'}} available</option></select></div><div class="field"><label>Quantity</label><input type="number" min="1" v-model.number="adhoc.qty"></div></div><div v-if="selectedItem" class="selected-summary"><b>{{selectedItem.name}}</b><span>{{selectedItem.sku}} · {{selectedItem.uom||'EA'}} · {{selectedItem.availableQty??selectedItem.qty}} available</span></div><label class="sub-label">Handling requirements</label><div class="chip-wrap"><button type="button" v-for="h in handlingOptions" :key="h" :class="['handling-chip',{selected:adhoc.specialHandling.includes(h)}]" @click="toggleHandling(h)">{{friendlyHandling(h)}}</button></div></div>
<div class="form-section"><h4>4. Delivery timing & instructions</h4><div class="form-grid"><div class="field"><label>Preferred delivery date</label><input type="date" v-model="adhoc.requestedDate"></div><div class="field"><label>Preferred time</label><select v-model="adhoc.requestedTimeWindow"><option value="ANYTIME">Anytime</option><option value="MORNING">Morning</option><option value="AFTERNOON">Afternoon</option><option value="EVENING">Evening</option></select></div></div><div class="field section-sm"><label>Destination instructions</label><textarea rows="4" v-model="adhoc.instructions" placeholder="Loading bay, security check-in, access restrictions, call-on-arrival instructions…"></textarea></div><div class="field section-sm"><label>Additional remarks</label><textarea rows="5" v-model="adhoc.notes" placeholder="Any other information warehouse management should know before planning this delivery."></textarea></div></div>
<div class="modal-actions"><button class="btn secondary" @click="showAdhoc=false">Cancel</button><button class="btn" :disabled="busy" @click="requestAdhoc">{{busy?'Submitting…':'Submit delivery request'}}</button></div></div></div>
<div v-if="showPlan" class="modal-overlay" @click.self="showPlan=false"><div class="card modal-dialog"><div class="section-head"><div><h3>Create delivery run</h3><span>{{selected.length}} delivery record(s) selected.</span></div><button class="mini-btn" @click="showPlan=false">Close</button></div><div class="form-grid"><div class="field"><label>Run name</label><input v-model="plan.name" placeholder="e.g. North retail morning run"></div><div class="field"><label>Scheduled start</label><input type="datetime-local" v-model="plan.scheduledAt"></div><div class="field"><label>Primary driver</label><select v-model="plan.primaryDriverId"><option value="">Select driver</option><option v-for="d in data.drivers" :key="d.id" :value="d.id">{{d.name}} · {{d.status}}</option></select></div><div class="field"><label>Standby driver</label><select v-model="plan.standbyDriverId"><option value="">None</option><option v-for="d in data.drivers" :key="d.id" :value="d.id" :disabled="d.id===plan.primaryDriverId">{{d.name}} · {{d.status}}</option></select></div><div class="field"><label>Vehicle</label><select v-model="plan.vehicleId"><option value="">Select vehicle</option><option v-for="v in data.vehicles" :key="v.id" :value="v.id">{{v.plate}} · {{v.capacityKg}} kg · {{v.status}}</option></select></div><div class="field"><label>Important note to driver</label><textarea rows="4" v-model="plan.managerNote" placeholder="Access restrictions, fragile cargo, handover requirements…"></textarea></div></div><div class="modal-actions"><button class="btn secondary" @click="showPlan=false">Cancel</button><button class="btn" :disabled="busy" @click="createRoute">{{busy?'Creating…':'Create & assign route'}}</button></div></div></div>
</template>
