<script setup>
import { onMounted, ref } from 'vue';
import { api } from '../api';
import { useAuthStore } from '../stores/auth';
const auth=useAuthStore();
const type=ref('process'),preview=ref([]),deliveries=ref([]),incidents=ref([]),invoices=ref([]),utilityBills=ref([]),branding=ref({}),saving=ref(false),selectedDelivery=ref(''),selectedIncident=ref(''),selectedInvoice=ref(''),selectedUtility=ref('');
async function load(){preview.value=(await api.get(`/reports/${type.value}`)).data.rows.slice(0,15)}
async function download(format){const r=await api.get(`/reports/${type.value}?format=${format}`,{responseType:'blob'});saveBlob(r.data,`${type.value}-report.${format}`)}
function saveBlob(blob,name){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
async function doc(kind,id,params=''){const r=await api.get(`/documents/${kind}/${id}${params}`,{responseType:'blob'});saveBlob(r.data,`${kind}-${id}.pdf`)}
async function refresh(){const [d,i,n,u,b]=await Promise.all([api.get('/deliveries'),api.get('/incidents'),api.get('/invoices'),api.get('/utilityBills'),api.get('/branding')]);deliveries.value=d.data;incidents.value=i.data;invoices.value=n.data;utilityBills.value=u.data;branding.value=b.data}
async function saveBrand(){saving.value=true;try{branding.value=(await api.patch('/branding',branding.value)).data}finally{saving.value=false}}
async function logo(e){const file=e.target.files?.[0];if(!file)return;const f=new FormData();f.append('logo',file);branding.value=(await api.post('/branding/logo',f)).data}
onMounted(refresh);
</script>
<template>
<div class="card modal-card"><div class="section-head"><div><h3>Professional reports & operational documents</h3><span>Generate audit exports and real-world business documents with controlled records and sign-off evidence.</span></div></div><div style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><div class="field" style="min-width:240px"><label>Audit report</label><select v-model="type"><option value="process">Process event log</option><option value="deliveries">Delivery register</option><option value="incidents">Incident register</option><option value="invoices">Invoice register</option><option value="utilities">Utility consumption</option><option value="meters">Meter estate</option></select></div><button class="btn secondary" @click="load">Preview</button><button class="btn secondary" @click="download('csv')">Export CSV</button><button class="btn" @click="download('pdf')">Export PDF</button></div></div>

<div v-if="preview.length" class="card section table-wrap"><div class="section-head"><div><h3>Preview</h3><span>First 15 records</span></div></div><table class="table"><thead><tr><th v-for="k in Object.keys(preview[0])" :key="k">{{k}}</th></tr></thead><tbody><tr v-for="r in preview" :key="r.id"><td v-for="k in Object.keys(preview[0])" :key="k">{{typeof r[k]==='object'?JSON.stringify(r[k]):r[k]}}</td></tr></tbody></table></div>

<div class="card section"><div class="section-head"><div><h3>Operational documents</h3><span>Documents formatted for real warehouse, logistics, billing and handover workflows.</span></div></div><div class="doc-grid">
<div class="doc-card"><b>Delivery Order / Proof of Delivery</b><span>Driver instructions and customer-signed goods receipt.</span><select v-model="selectedDelivery"><option disabled value="">Select delivery</option><option v-for="d in deliveries" :key="d.id" :value="d.id">{{d.id}} · {{String(d.status).replaceAll('_',' ')}}</option></select><div><button class="btn secondary" :disabled="!selectedDelivery" @click="doc('delivery',selectedDelivery,'?type=DELIVERY_ORDER')">Delivery Order PDF</button><button class="btn" :disabled="!selectedDelivery" @click="doc('delivery',selectedDelivery,'?type=POD')">Signed POD PDF</button></div></div>
<div class="doc-card"><b>Incident Report</b><span>Exception, investigation and corrective action record.</span><select v-model="selectedIncident"><option disabled value="">Select incident</option><option v-for="x in incidents" :key="x.id" :value="x.id">{{x.id}} · {{x.title||x.type}}</option></select><button class="btn" :disabled="!selectedIncident" @click="doc('incident',selectedIncident)">Incident Report PDF</button></div>
<div class="doc-card"><b>Commercial Invoice</b><span>Rent, utilities and service-charge invoice.</span><select v-model="selectedInvoice"><option disabled value="">Select invoice</option><option v-for="x in invoices" :key="x.id" :value="x.id">{{x.id}} · {{x.currency}} {{x.total}}</option></select><button class="btn" :disabled="!selectedInvoice" @click="doc('invoice',selectedInvoice)">Invoice PDF</button></div>
<div class="doc-card"><b>Energy & Water Statement</b><span>Metered usage and tenant utility chargeback statement.</span><select v-model="selectedUtility"><option disabled value="">Select statement</option><option v-for="x in utilityBills" :key="x.id" :value="x.id">{{x.id}} · {{x.period}}</option></select><button class="btn" :disabled="!selectedUtility" @click="doc('utility',selectedUtility)">Utility Statement PDF</button></div>
</div></div>

<div v-if="auth.user?.role==='OWNER'" class="card section"><div class="section-head"><div><h3>Document branding</h3><span>Your company details are printed on generated documents. Upload your actual company logo before production use.</span></div></div><div class="brand-form"><div class="field"><label>Legal company name</label><input v-model="branding.legalName"/></div><div class="field"><label>Registration number</label><input v-model="branding.registrationNo"/></div><div class="field"><label>Company address</label><input v-model="branding.address"/></div><div class="field"><label>Phone</label><input v-model="branding.phone"/></div><div class="field"><label>Email</label><input v-model="branding.email"/></div><div class="field"><label>Website</label><input v-model="branding.website"/></div></div><div class="brand-actions"><label class="btn secondary upload-btn">Upload logo<input type="file" accept="image/png,image/jpeg" @change="logo"/></label><span v-if="branding.logoPath">✓ Logo configured</span><button class="btn" :disabled="saving" @click="saveBrand">{{saving?'Saving…':'Save company details'}}</button></div></div>
</template>
