<script setup>
import { ref,onMounted } from 'vue'; import { api } from '../api';
const data=ref({jobs:[],cargoProfiles:[],metrics:{}}),show=ref(false); const form=ref({mode:'SEA',serviceType:'FCL',origin:'',destination:'',cargoClass:'GENERAL',incoterm:'FOB',customsStatus:'PENDING'}); async function load(){data.value=(await api.get('/freight/overview')).data} async function add(){await api.post('/freight-jobs',form.value);show.value=false;await load()} onMounted(load)
</script>
<template><div class="hero"><div><h1>Freight & Cargo</h1><p>Manage road, air and sea shipments, customs documents and special handling requirements in one place.</p></div><button class="btn" @click="show=true">Create shipment</button></div>
<div class="grid4 section"><div class="card metric"><div class="label">AIR SHIPMENTS</div><div class="value">{{data.metrics.air}}</div></div><div class="card metric"><div class="label">SEA SHIPMENTS</div><div class="value">{{data.metrics.sea}}</div></div><div class="card metric"><div class="label">FRAGILE</div><div class="value">{{data.metrics.fragile}}</div></div><div class="card metric"><div class="label">CUSTOMS PENDING</div><div class="value">{{data.metrics.customsPending}}</div></div></div>
<div class="section card table-wrap"><div class="table-title"><div class="section-head"><div><h3>Freight shipments</h3><span>Door → warehouse → port/airport → customs → destination</span></div></div></div><table class="table"><thead><tr><th>Job</th><th>Mode</th><th>Route</th><th>Carrier / reference</th><th>Cargo</th><th>Customs</th><th>Status</th></tr></thead><tbody><tr v-for="j in data.jobs" :key="j.id"><td><b>{{j.id}}</b><br><small>{{j.serviceType}}</small></td><td><span class="pill">{{j.mode}}</span></td><td>{{j.origin}} → {{j.destination}}</td><td>{{j.carrier}}<br><small>{{j.containerNo||j.awb||j.vesselFlight}}</small></td><td><span class="tag">{{j.cargoClass}}</span><br><small>{{j.incoterm}}</small></td><td>{{j.customsStatus}}</td><td><span class="pill">{{j.status}}</span></td></tr></tbody></table></div>
<div class="section"><div class="section-head"><div><h3>Special cargo handling rules</h3><span>Handling rules become mandatory workflow checkpoints</span></div></div><div class="kpi-grid"><div v-for="c in data.cargoProfiles" :key="c.id" class="card metric"><div class="label">{{c.name.toUpperCase()}}</div><div style="margin-top:10px"><span v-for="f in c.flags" class="tag">{{f}}</span></div><p class="note">{{c.handling.join(' · ')}}</p></div></div></div>
<div class="section callout"><b>Niche scenarios included in the data model:</b> LCL/FCL containers, air waybills, cross-docking, bonded/customs hold, temperature excursions, shock/tilt events, dangerous goods/SDS, oversized cargo, high-value chain of custody, failed customs clearance, demurrage/detention, missed vessel/flight, partial shipment, damaged cargo, quarantine and returns.</div>
<div v-if="show" class="modal-overlay"><div class="card modal-dialog"><div class="section-head"><h3>Create shipment</h3><button class="mini-btn" @click="show=false">Close</button></div><div class="form-grid"><div class="field"><label>Transport method</label><select v-model="form.mode"><option>SEA</option><option>AIR</option><option>ROAD</option><option>RAIL</option><option>MULTIMODAL</option></select></div><div class="field"><label>Freight service</label><select v-model="form.serviceType"><option>FCL</option><option>LCL</option><option>AIR_FREIGHT</option><option>COURIER</option><option>PROJECT_CARGO</option></select></div><div class="field"><label>Origin</label><input v-model="form.origin"></div><div class="field"><label>Destination</label><input v-model="form.destination"></div><div class="field"><label>Cargo handling type</label><select v-model="form.cargoClass"><option>GENERAL</option><option>FRAGILE</option><option>COLD_CHAIN</option><option>HAZMAT</option><option>HIGH_VALUE</option><option>OVERSIZED</option></select></div><div class="field"><label>Incoterm</label><select v-model="form.incoterm"><option>EXW</option><option>FOB</option><option>CIF</option><option>CIP</option><option>DAP</option><option>DDP</option></select></div></div><button class="btn section" @click="add">Create shipment</button></div></div></template>
