<script setup>
import {computed,onMounted,ref,watch} from 'vue';import {api} from '../api';import {useAuthStore} from '../stores/auth';
const auth=useAuthStore(),data=ref({inventory:[],ledger:[]}),ops=ref({goodsRequests:[],warehouses:[],stores:[],tenants:[],inventory:[]}),busy=ref(false),showRequest=ref(false),showAdjust=ref(false);
const form=ref({tenantId:'',sourceWarehouseId:'',destinationId:'',requestedFor:'',sku:'',qty:1,notes:''});
const adjust=ref({tenantId:'',locationType:'WAREHOUSE',locationId:'',sku:'',qtyDelta:0,reason:''});
const manager=computed(()=>['OWNER','WAREHOUSE_MANAGER'].includes(auth.user?.role));const fmt=n=>Number(n||0).toLocaleString();
const activeTenant=computed(()=>auth.user?.role==='TENANT'?auth.user.tenantId:form.value.tenantId);
const requestStores=computed(()=>ops.value.stores?.filter(s=>!activeTenant.value||s.tenantId===activeTenant.value)||[]);
const requestWarehouses=computed(()=>ops.value.warehouses||[]);
const requestInventory=computed(()=>data.value.inventory.filter(i=>(!activeTenant.value||i.tenantId===activeTenant.value)&&i.locationType==='WAREHOUSE'&&(!form.value.sourceWarehouseId||i.locationId===form.value.sourceWarehouseId)));
const requestItems=computed(()=>{const m=new Map();for(const i of requestInventory.value)if(!m.has(i.sku))m.set(i.sku,i);return [...m.values()]});
const adjustTenant=computed(()=>adjust.value.tenantId||auth.user?.tenantId);
const adjustLocations=computed(()=>adjust.value.locationType==='WAREHOUSE'?(ops.value.warehouses||[]):(ops.value.stores||[]).filter(s=>!adjustTenant.value||s.tenantId===adjustTenant.value));
const adjustItems=computed(()=>data.value.inventory.filter(i=>(!adjustTenant.value||i.tenantId===adjustTenant.value)&&i.locationType===adjust.value.locationType&&(!adjust.value.locationId||i.locationId===adjust.value.locationId)));
function notify(title,message,type='success'){window.dispatchEvent(new CustomEvent('flowdepot:toast',{detail:{title,message,type}}))}
const whName=id=>ops.value.warehouses?.find(w=>w.id===id)?.name||id;const storeName=id=>ops.value.stores?.find(s=>s.id===id)?.name||id;const tenantName=id=>ops.value.tenants?.find(t=>t.id===id)?.name||'Customer';const itemName=sku=>data.value.inventory.find(i=>i.sku===sku)?.name||sku;
async function load(){const [a,b]=await Promise.all([api.get('/inventory-control'),api.get('/operations/overview')]);data.value=a.data;ops.value=b.data}onMounted(load);
function openRequest(){form.value={tenantId:auth.user?.role==='TENANT'?auth.user.tenantId:'',sourceWarehouseId:ops.value.warehouses?.[0]?.id||'',destinationId:'',requestedFor:'',sku:'',qty:1,notes:''};showRequest.value=true}
function openAdjust(){adjust.value={tenantId:ops.value.tenants?.[0]?.id||'',locationType:'WAREHOUSE',locationId:ops.value.warehouses?.[0]?.id||'',sku:'',qtyDelta:0,reason:''};showAdjust.value=true}
watch(()=>form.value.tenantId,()=>{form.value.destinationId='';form.value.sku=''});watch(()=>form.value.sourceWarehouseId,()=>{form.value.sku=''});watch(()=>adjust.value.tenantId,()=>adjust.value.sku='');watch(()=>adjust.value.locationId,()=>adjust.value.sku='');
async function requestGoods(){if(manager.value&&!form.value.tenantId)return notify('Customer required','Choose the customer whose stock is being requested.','error');if(!form.value.sourceWarehouseId||!form.value.destinationId||!form.value.sku||Number(form.value.qty)<1)return notify('Incomplete request','Choose the source warehouse, destination, product and quantity.','error');busy.value=true;try{const r=await api.post('/goods-requests',{tenantId:manager.value?form.value.tenantId:undefined,sourceWarehouseId:form.value.sourceWarehouseId,destinationType:'STORE',destinationId:form.value.destinationId,requestedFor:form.value.requestedFor||undefined,items:[{sku:form.value.sku,qty:Number(form.value.qty)}],notes:form.value.notes});showRequest.value=false;notify('Goods request submitted',`${r.data.id} was sent for warehouse approval.`);await load()}catch(e){notify('Unable to submit',e.response?.data?.error||e.message,'error')}finally{busy.value=false}}
async function review(r,status){try{await api.patch(`/goods-requests/${r.id}/review`,{status});notify(status==='APPROVED'?'Stock reserved':'Request rejected',`${r.id} was ${status.toLowerCase()}.`);await load()}catch(e){notify('Action failed',e.response?.data?.error||e.message,'error')}}
async function createDelivery(r){try{await api.post(`/goods-requests/${r.id}/create-delivery`,{});notify('Delivery created',`${r.id} is now in the delivery planning queue.`);await load()}catch(e){notify('Action failed',e.response?.data?.error||e.message,'error')}}
async function submitAdjust(){if(!adjust.value.tenantId||!adjust.value.locationId||!adjust.value.sku||!adjust.value.reason.trim()||!Number(adjust.value.qtyDelta))return notify('Adjustment incomplete','Choose customer, location and product, then enter a non-zero change and reason.','error');busy.value=true;try{const r=await api.post('/inventory/adjustments',{...adjust.value,qtyDelta:Number(adjust.value.qtyDelta)});showAdjust.value=false;notify(r.status===202?'Approval required':'Stock updated',r.status===202?'Adjustment was submitted for maker/checker approval.':'The stock ledger has been updated.');await load()}catch(e){notify('Unable to adjust stock',e.response?.data?.error||e.message,'error')}finally{busy.value=false}}
</script>
<template>
<div class="section-head"><div><h3>Inventory control</h3><span>On-hand, reserved and available stock are separated. Quantity changes are ledger transactions, never silent overwrites.</span></div><div class="actions-row"><button class="btn" @click="openRequest">Request goods</button><button v-if="manager" class="btn secondary" @click="openAdjust">Stock adjustment</button></div></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Product</th><th>Location</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Unit cost</th><th>Unit price</th><th>Handling</th></tr></thead><tbody><tr v-for="i in data.inventory" :key="i.id"><td><b>{{i.name}}</b><br><small>{{i.sku}} · {{i.uom||'EA'}}</small></td><td>{{i.locationType==='WAREHOUSE'?whName(i.locationId):storeName(i.locationId)}}<br><small>{{i.locationType.toLowerCase()}}</small></td><td>{{fmt(i.qty)}}</td><td>{{fmt(i.reservedQty)}}</td><td><b>{{fmt(i.availableQty)}}</b></td><td>${{Number(i.unitCost||0).toFixed(2)}}</td><td>${{Number(i.unitPrice||0).toFixed(2)}}</td><td><span v-for="h in i.handlingRules||[]" :key="h" class="pill warn" style="margin:2px">{{h.replaceAll('_',' ')}}</span></td></tr></tbody></table></div>
<div class="section-head section"><div><h3>Goods requests</h3><span>Customer/store replenishment requests are approved before stock is reserved and converted into a delivery.</span></div></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Request</th><th>Customer</th><th>From → To</th><th>Items</th><th>Requested for</th><th>Status</th><th v-if="manager">Actions</th></tr></thead><tbody><tr v-for="r in ops.goodsRequests" :key="r.id"><td><b>{{r.id}}</b><br><small>{{r.notes}}</small></td><td>{{tenantName(r.tenantId)}}</td><td>{{whName(r.sourceWarehouseId)}} → {{storeName(r.destinationId)}}</td><td><span v-for="x in r.items" :key="x.sku">{{itemName(x.sku)}} × {{x.qty}}<br></span></td><td>{{r.requestedFor?new Date(r.requestedFor).toLocaleString():'-'}}</td><td><span class="pill">{{r.status}}</span></td><td v-if="manager"><div class="actions-row"><button v-if="r.status==='REQUESTED'" class="btn" @click="review(r,'APPROVED')">Approve & reserve</button><button v-if="r.status==='REQUESTED'" class="btn secondary" @click="review(r,'REJECTED')">Reject</button><button v-if="r.status==='APPROVED'" class="btn" @click="createDelivery(r)">Create delivery</button></div></td></tr></tbody></table></div>
<div class="section-head section"><div><h3>Stock ledger</h3><span>Append-only operational history showing why stock changed.</span></div></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Time</th><th>Product</th><th>Location</th><th>Movement</th><th>Change</th><th>Before → After</th><th>Reference</th><th>Actor</th></tr></thead><tbody><tr v-for="r in data.ledger" :key="r.id"><td>{{new Date(r.createdAt).toLocaleString()}}</td><td>{{itemName(r.sku)}}<br><small>{{r.sku}}</small></td><td>{{r.locationType==='STORE'?storeName(r.locationId):whName(r.locationId)}}</td><td>{{r.movementType.replaceAll('_',' ')}}</td><td><b>{{r.qtyDelta>0?'+':''}}{{r.qtyDelta}}</b></td><td>{{r.qtyBefore}} → {{r.qtyAfter}}</td><td>{{r.referenceType.replaceAll('_',' ')}}<br><small>{{r.referenceId}}</small></td><td>{{r.actor}}</td></tr></tbody></table></div>
<div v-if="showRequest" class="modal-overlay" @click.self="showRequest=false"><div class="card modal-dialog"><div class="section-head"><div><h3>Request goods</h3><span>Choose familiar warehouse, store and product names. Internal IDs stay hidden.</span></div><button class="mini-btn" @click="showRequest=false">Close</button></div><div class="form-grid"><div v-if="manager" class="field" style="grid-column:1/-1"><label>Customer / tenant</label><select v-model="form.tenantId"><option value="">Choose customer</option><option v-for="t in ops.tenants" :key="t.id" :value="t.id">{{t.name}}</option></select></div><div class="field"><label>Source warehouse</label><select v-model="form.sourceWarehouseId"><option value="">Choose warehouse</option><option v-for="w in requestWarehouses" :key="w.id" :value="w.id">{{w.name}} — {{w.address}}</option></select></div><div class="field"><label>Destination store</label><select v-model="form.destinationId"><option value="">Choose store</option><option v-for="s in requestStores" :key="s.id" :value="s.id">{{s.name}} — {{s.address}}</option></select></div><div class="field"><label>Product / item</label><select v-model="form.sku"><option value="">Choose product</option><option v-for="i in requestItems" :key="i.sku" :value="i.sku">{{i.name}} · {{i.availableQty}} {{i.uom||'units'}} available</option></select></div><div class="field"><label>Quantity</label><input type="number" min="1" v-model.number="form.qty"></div><div class="field"><label>Requested date/time</label><input type="datetime-local" v-model="form.requestedFor"></div><div class="field" style="grid-column:1/-1"><label>Notes / replenishment reason</label><textarea rows="4" v-model="form.notes" placeholder="e.g. Weekend replenishment, promotion stock, urgent replacement…"></textarea></div></div><div class="modal-actions"><button class="btn secondary" @click="showRequest=false">Cancel</button><button class="btn" :disabled="busy" @click="requestGoods">{{busy?'Submitting…':'Submit goods request'}}</button></div></div></div>
<div v-if="showAdjust" class="modal-overlay" @click.self="showAdjust=false"><div class="card modal-dialog"><div class="section-head"><div><h3>Controlled stock adjustment</h3><span>Every change requires a reason and is written to the stock ledger. Large changes require a different approver.</span></div><button class="mini-btn" @click="showAdjust=false">Close</button></div><div class="form-grid"><div class="field"><label>Customer / tenant</label><select v-model="adjust.tenantId"><option value="">Choose customer</option><option v-for="t in ops.tenants" :key="t.id" :value="t.id">{{t.name}}</option></select></div><div class="field"><label>Location type</label><select v-model="adjust.locationType"><option value="WAREHOUSE">Warehouse</option><option value="STORE">Store</option></select></div><div class="field"><label>Location</label><select v-model="adjust.locationId"><option value="">Choose location</option><option v-for="l in adjustLocations" :key="l.id" :value="l.id">{{l.name}} — {{l.address}}</option></select></div><div class="field"><label>Product / item</label><select v-model="adjust.sku"><option value="">Choose product</option><option v-for="i in adjustItems" :key="i.sku" :value="i.sku">{{i.name}} · current {{i.qty}} {{i.uom||'units'}}</option></select></div><div class="field"><label>Quantity change</label><input type="number" v-model.number="adjust.qtyDelta" placeholder="Use - for reduction"></div><div class="field" style="grid-column:1/-1"><label>Reason *</label><textarea rows="4" v-model="adjust.reason" placeholder="Explain why the physical stock differs. This becomes part of the permanent audit trail."></textarea></div></div><div class="modal-actions"><button class="btn secondary" @click="showAdjust=false">Cancel</button><button class="btn" :disabled="busy||!adjust.reason" @click="submitAdjust">{{busy?'Submitting…':'Submit adjustment'}}</button></div></div></div>
</template>
