<script setup>
import { computed,onMounted,ref } from 'vue';
import { api } from '../api';
import { useAuthStore } from '../stores/auth';
const auth=useAuthStore(),contacts=ref([]),stores=ref([]),tenants=ref([]),distributions=ref([]),editing=ref(null);
const roles=['RECEIVING','STORE_MANAGER','LOGISTICS','FINANCE','OTHER'];
const tenantStores=computed(()=>stores.value.filter(s=>!editing.value?.tenantId||s.tenantId===editing.value.tenantId));
const storeName=id=>stores.value.find(s=>s.id===id)?.name||'Company-wide';
const tenantName=id=>tenants.value.find(t=>t.id===id)?.name||id;
async function load(){const x=(await api.get('/pod-contacts')).data;contacts.value=x.contacts;stores.value=x.stores;tenants.value=x.tenants;distributions.value=(await api.get('/pod-distributions')).data;}
function add(){editing.value={tenantId:auth.user?.role==='TENANT'?auth.user.tenantId:(tenants.value[0]?.id||''),storeId:'',name:'',email:'',phone:'',role:'RECEIVING',receivePod:true,receiveAlerts:false,active:true};}
function edit(c){editing.value={...c,storeId:c.storeId||''};}
async function save(){if(editing.value.id)await api.patch(`/pod-contacts/${editing.value.id}`,editing.value);else await api.post('/pod-contacts',editing.value);editing.value=null;await load();}
async function disable(c){if(!confirm(`Disable ${c.name}? Historical POD records will remain unchanged.`))return;await api.delete(`/pod-contacts/${c.id}`);await load();}
async function retry(d){await api.post(`/pod-distributions/${d.id}/retry`);await load();}
const fmt=t=>t?new Date(t).toLocaleString():'—';
onMounted(load);
</script>
<template>
<div class="section-head"><div><h3>POD receiving contacts</h3><span>Configure one or more receiving, store manager and company contacts. FlowDepot snapshots the applicable recipients when a signed POD is issued.</span></div><button class="btn" @click="add">Add contact</button></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Location</th><th>Contact</th><th>Role</th><th>POD</th><th>Alerts</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="c in contacts" :key="c.id"><td><b>{{storeName(c.storeId)}}</b><br><small>{{tenantName(c.tenantId)}}</small></td><td>{{c.name}}<br><small>{{c.email||c.phone}}</small></td><td>{{c.role.replaceAll('_',' ')}}</td><td>{{c.receivePod?'✓ Send':'—'}}</td><td>{{c.receiveAlerts?'✓':'—'}}</td><td><span class="pill" :class="c.active?'good':''">{{c.active?'ACTIVE':'INACTIVE'}}</span></td><td><button class="btn secondary" @click="edit(c)">Edit</button> <button v-if="c.active" class="mini-btn" @click="disable(c)">Disable</button></td></tr></tbody></table></div>
<div class="section-head section"><div><h3>POD distribution queue</h3><span>Document generation and distribution are separate. Email/SMS delivery failures do not invalidate the completed delivery or signed POD.</span></div></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Delivery</th><th>Recipient snapshot</th><th>Channel</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody><tr v-for="d in distributions.slice(0,40)" :key="d.id"><td><b>{{d.deliveryId}}</b><br><small>{{d.documentType}}</small></td><td>{{d.recipient?.name}} · {{String(d.recipient?.role||'').replaceAll('_',' ')}}<br><small>{{d.recipient?.email||d.recipient?.phone}}</small></td><td>{{d.channel}}</td><td><span class="pill" :class="d.status==='DELIVERED'?'good':d.status==='FAILED'?'warn':''">{{d.status}}</span></td><td>{{fmt(d.createdAt)}}</td><td><button v-if="d.status==='FAILED'" class="btn secondary" @click="retry(d)">Retry</button></td></tr><tr v-if="!distributions.length"><td colspan="6">No PODs have been distributed yet. Complete a delivery sign-off to create distribution records.</td></tr></tbody></table></div>
<div v-if="editing" class="modal-overlay" @click.self="editing=null"><div class="card modal-dialog"><div class="section-head"><div><h3>{{editing.id?'Edit':'Add'}} POD contact</h3><span>Multiple people can share the same role at the same store.</span></div><button class="mini-btn" @click="editing=null">Close</button></div><div class="form-grid"><div v-if="auth.user?.role!=='TENANT'" class="field"><label>Tenant / customer</label><select v-model="editing.tenantId"><option v-for="t in tenants" :value="t.id" :key="t.id">{{t.name}}</option></select></div><div class="field"><label>Store / location</label><select v-model="editing.storeId"><option value="">Company-wide</option><option v-for="s in tenantStores" :value="s.id" :key="s.id">{{s.name}}</option></select></div><div class="field"><label>Name / team</label><input v-model="editing.name" placeholder="e.g. Receiving Desk or Amy Lim"/></div><div class="field"><label>Role</label><select v-model="editing.role"><option v-for="r in roles" :value="r" :key="r">{{r.replaceAll('_',' ')}}</option></select></div><div class="field"><label>Email</label><input v-model="editing.email" type="email"/></div><div class="field"><label>Phone</label><input v-model="editing.phone"/></div><div class="field check-field"><label><input type="checkbox" v-model="editing.receivePod"/> Receive signed POD</label></div><div class="field check-field"><label><input type="checkbox" v-model="editing.receiveAlerts"/> Receive operational alerts</label></div></div><button class="btn section" @click="save">Save contact</button></div></div>
</template>