<script setup>
import { onMounted,onUnmounted,ref,computed } from 'vue';
import { api,API_BASE } from '../api'; import { io } from '../../../../shared/realtime';
const payload=ref(null),scenario=ref('NORMAL_DAY'),speed=ref(10),mode=ref('DEMO'),busy=ref(false); let socket;
const state=computed(()=>payload.value?.state||{}); const feed=computed(()=>payload.value?.feed||[]); const telemetry=computed(()=>payload.value?.telemetry||[]);
async function load(){payload.value=(await api.get('/simulation/status')).data}
async function action(name,body={}){busy.value=true;try{await api.post(`/simulation/${name}`,body);await load()}finally{busy.value=false}}
async function start(){await action('start',{scenario:scenario.value,speed:speed.value,mode:mode.value})}
const label=v=>String(v||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase());
const whName=id=>({'WH-01':'Warehouse A','WH-02':'Warehouse B','WH-03':'Warehouse C'}[id]||id);
onMounted(async()=>{await load();socket=io(API_BASE.replace('/api',''));socket.on('simulation-event',()=>load());socket.on('simulation-telemetry',()=>load());socket.on('simulation-status',()=>load())});onUnmounted(()=>socket?.disconnect());
</script>
<template><div>
<div class="hero sim-hero"><div><div class="eyebrow">SAFE DEMO & TRAINING</div><h1>Live Simulation</h1><p>Run realistic goods requests, inventory reservation, dispatch planning, driver instructions, delivery, POD, notification and utility events through the same platform workflows without affecting live operations.</p></div><div class="sim-badge" :class="state.running?'on':''">{{state.running?'SIMULATION RUNNING':'SIMULATION IDLE'}}</div></div>
<div class="sim-warning">🧪 <b>Simulation Mode</b> — all generated records are clearly tagged and can be reset without touching production records.</div>
<div class="card sim-control section"><div><label>Mode</label><select v-model="mode"><option>DEMO</option><option>TRAINING</option></select></div><div><label>Scenario</label><select v-model="scenario"><option value="FULL_OPERATIONS">Full warehouse-to-POD workflow</option><option value="NORMAL_DAY">Normal day</option><option value="PEAK_OPERATIONS">Peak operations</option><option value="VEHICLE_BREAKDOWN">Vehicle breakdown</option><option value="UTILITY_SPIKE">Utility spike</option></select></div><div><label>Speed</label><select v-model.number="speed"><option :value="1">1×</option><option :value="5">5×</option><option :value="10">10×</option><option :value="20">20×</option><option :value="60">60×</option></select></div><div class="sim-actions"><button class="btn" :disabled="busy" @click="start">Start new run</button><button class="btn secondary" :disabled="busy||!state.runId" @click="action(state.running?'pause':'resume')">{{state.running?'Pause':'Resume'}}</button><button class="mini-btn" :disabled="busy" @click="action('step',{scenario,speed})">Step once</button><button class="mini-btn danger-lite" :disabled="busy||!state.runId" @click="action('reset')">Reset</button></div></div>
<div class="grid4 section"><div class="card metric"><div class="label">SCENARIO</div><div class="value small-value">{{label(state.scenario)}}</div><div class="sub">{{state.mode||'DEMO'}} mode</div></div><div class="card metric"><div class="label">SIMULATION TICK</div><div class="value">{{state.tick||0}}</div><div class="sub">~{{state.elapsedSimMinutes||0}} simulated min</div></div><div class="card metric"><div class="label">SIMULATED JOBS</div><div class="value">{{payload?.deliveries?.length||0}}</div><div class="sub">Safe isolated records</div></div><div class="card metric"><div class="label">EVENTS</div><div class="value">{{feed.length}}</div><div class="sub">Live workflow feed</div></div></div>
<div class="split section"><div class="card"><div class="section-head" style="padding:16px 16px 0"><div><h3>Live operations feed</h3><span>Dashboard, mobile and alerts update from these events</span></div></div><div class="sim-feed"><div v-if="!feed.length" class="empty">Start a scenario to generate operational events.</div><div v-for="e in feed" :key="e.id" class="sim-event"><span class="sim-dot" :class="e.level"></span><div><b>{{e.title}}</b><p>{{e.message}}</p><small>{{new Date(e.createdAt).toLocaleTimeString()}}</small></div></div></div></div>
<div class="card"><div class="section-head" style="padding:16px 16px 0"><div><h3>Live utility telemetry</h3><span>Simulated raw readings for Energy & Water</span></div></div><div class="sim-feed"><div v-if="!telemetry.length" class="empty">No simulated meter readings yet.</div><div v-for="r in telemetry.slice(0,12)" :key="r.id" class="telemetry-row"><div><b>{{whName(r.warehouseId)}}</b><small>{{new Date(r.timestamp).toLocaleTimeString()}}</small></div><span>{{r.electricityKw}} kW</span><span>{{r.waterM3h}} m³/h</span></div></div></div></div>
</div></template>